Repository newrelic/newrelic-ruby-agent, pull requests merged in 2020-09, with the labels that each got.

#452 resolves Issue 451 and possibly 450
  CHANGELOG.md
  lib/new_relic/agent/http_clients/uri_util.rb
  test/new_relic/agent/http_clients/uri_util_test.rb
Labels: perf:multiple-per-transaction, version:6.13.1

#458 Reduce gem package size
  newrelic_rpm.gemspec
Labels: accepted, version:upcoming

#408 ci: Add Open Source Policy Workflow
  .github/workflows/repolinter.yml
Labels: stale
