Repository newrelic/newrelic-ruby-agent, pull requests merged in 2020-10, with the labels that each got.

#468 Add checks for nil middleware class in use_with_newrelic
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/rack.rb
Labels: perf:startup, version:upcoming

#465 fixes dependency check for Redis instrumentation
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/redis.rb
Labels: version:6.14.0

#476 Updated the memory sampler to recognize macOS Big Sur
  CHANGELOG.md
  lib/new_relic/agent/samplers/memory_sampler.rb
Labels: perf:startup, version:6.14.0
