Repository newrelic/newrelic-ruby-agent, pull requests merged in 2020-12, with the labels that each got.

#511 resolve infinite recursion when airbrake is present
  lib/new_relic/agent/instrumentation/net.rb
  lib/new_relic/agent/instrumentation/net_prepend.rb
  lib/new_relic/dependency_detection.rb
Labels: perf:startup, version:6.15.0

#514 updated json gem for Ruby 3.0+
  test/multiverse/lib/multiverse/output_collector.rb
  test/multiverse/suites/json/Envfile
Labels: version:6.15.0

#505 Force install exit handler flag
  CHANGELOG.md
  lib/new_relic/agent/agent.rb
  lib/new_relic/agent/configuration/default_source.rb
  test/new_relic/agent/agent/start_test.rb
Labels: perf:startup, version:6.15.0

#506 Disable the stale bot
  .github/workflows/stale.yml
Labels: version:6.15.0

#521 multiple bug fixes
  CHANGELOG.md
  lib/new_relic/agent/span_event_primitive.rb
  lib/new_relic/agent/transaction/abstract_segment.rb
  lib/new_relic/supportability_helper.rb
  test/new_relic/agent/span_event_primitive_test.rb
Labels: perf:multiple-per-transaction, version:6.15.0

#523 update to gRPC 1.34.0
  infinite_tracing/newrelic-infinite_tracing.gemspec
Labels: version:6.15.0

#525 509 handle failed precondition response
  infinite_tracing/lib/infinite_tracing/client.rb
  infinite_tracing/test/infinite_tracing/connection_test.rb
  infinite_tracing/test/support/fake_trace_observer.rb
  infinite_tracing/test/support/fake_trace_observer_helpers.rb
Labels: perf:harvest, version:6.15.0
