Repository newrelic/newrelic-ruby-agent, pull requests merged in 2020-08, with the labels that each got.

#364 Remove NewRelic::Metrics file because there are not references to it
  lib/new_relic/agent.rb
  lib/new_relic/metrics.rb
Labels: in review

#372 PR 359: Prevent reconnect attempts during shutdowns
  CHANGELOG.md
  lib/new_relic/agent/agent.rb
  test/new_relic/agent/agent_test.rb
Labels: version:6.13.0

#369 Decrease allocations for span attributes
  lib/new_relic/agent/transaction/segment.rb
Labels: version:6.13.0

#377 Don't modify params from the caller
  lib/new_relic/agent.rb
Labels: accepted, version:6.13.0

#406 Ensure preconnect never uses redirect host
  CHANGELOG.md
  lib/new_relic/agent/new_relic_service.rb
  test/agent_helper.rb
  test/multiverse/suites/config_file_loading/config_file_loading_test.rb
  test/new_relic/agent/new_relic_service_test.rb
Labels: perf:startup, version:6.13.0
