Repository newrelic/newrelic-ruby-agent, pull requests merged in 2020-11, with the labels that each got.

#469 Use connection_db_config if it's available
  lib/new_relic/environment_report.rb
Labels: accepted, version:upcoming

#494 restores .erb to the search paths for config files
  CHANGELOG.md
  lib/new_relic/agent/configuration/default_source.rb
Labels: perf:startup, version:6.14.0

#492 request headers are now logged
  CHANGELOG.md
  lib/new_relic/agent/audit_logger.rb
  lib/new_relic/agent/distributed_tracing/cross_app_tracing.rb
  lib/new_relic/agent/new_relic_service.rb
  lib/new_relic/agent/transaction/distributed_tracer.rb
  lib/new_relic/agent/transaction/message_broker_segment.rb
  test/new_relic/agent/transaction/external_request_segment_test.rb
Labels: perf:harvest, version:upcoming

#495 fixed overzealous 2.7 changes
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/middleware_proxy.rb
  lib/new_relic/agent/instrumentation/rack.rb
Labels: perf:startup, version:6.14.0

#497 Updates for our github action workflows
  .github/workflows/assignproj.yml
  .github/workflows/ci.yml
  .github/workflows/pr_review_checklist.yml
  .github/workflows/release.yml
Labels: github

#499 Method tracers refactored
  .gitignore
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb
  lib/new_relic/agent/method_tracer.rb
  lib/new_relic/constants.rb
  test/new_relic/agent/method_tracer_params_test.rb
Labels: perf:startup, version:6.14.0
