Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-11, with the labels that each got.

#820 Use Dalli::Protocol::Binary rather than Dalli::Server
  lib/new_relic/agent/instrumentation/memcache/dalli.rb
  lib/new_relic/agent/instrumentation/memcache/helper.rb
  lib/new_relic/agent/instrumentation/memcache/prepend.rb
  test/multiverse/suites/memcache/Envfile
  test/multiverse/suites/memcache/dalli_test.rb
Labels: version:upcoming, community

#824 Disable instrumentation referencing Rails 2
  lib/new_relic/agent/instrumentation/rails/action_controller.rb
  lib/new_relic/agent/instrumentation/rails/action_web_service.rb
Labels: technical debt

#843 Add deprecated flag to error_collector.ignore_errors
  lib/new_relic/agent/configuration/default_source.rb
Labels: technical debt

#862 Delete duplicate settings
  newrelic.yml
Labels: community, pending-merge

#861 Prevent distributed tracing headers from emitting errors when agent not connected
  lib/new_relic/agent/distributed_tracing/trace_context_payload.rb
  lib/new_relic/agent/transaction/distributed_tracer.rb
  test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
  test/new_relic/agent/transaction/distributed_tracer_test.rb
  test/new_relic/http_client_test_cases.rb
Labels: pending-merge
