Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-09, with the labels that each got.

#768 Load hash value for configuration option from yaml file
  CHANGELOG.md
  lib/new_relic/agent/configuration/manager.rb
  lib/new_relic/agent/configuration/yaml_source.rb
  test/config/newrelic.yml
  test/new_relic/agent/configuration/yaml_source_test.rb
Labels: bug

#775 Remove deprecated method External#start_segment
  CHANGELOG.md
  lib/new_relic/agent/external.rb
  test/new_relic/agent/external_test.rb
  test/new_relic/agent/supportability_test.rb
Labels: documentation, version: 8.0.0

#777 Accept Integers for ignored status codes in YAML config
  lib/new_relic/agent/error_filter.rb
  test/new_relic/agent/error_filter_test.rb
Labels: pending-merge

#781 Bugfix/net http ipv6 requests
  lib/new_relic/agent/http_clients/net_http_wrappers.rb
  test/new_relic/net_http_test_cases.rb
Labels: pending-merge

#799 [BUGFIX] add_method_tracer errors on BasicObject methods
  lib/new_relic/agent/method_tracer.rb
  test/new_relic/agent/method_tracer_test.rb
Labels: bug, community
