Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-01, with the labels that each got.

#531 Default net_prepend_instrumentation to false
  CHANGELOG.md
  lib/new_relic/agent/configuration/default_source.rb
  test/multiverse/suites/net_http_prepend/config/newrelic.yml
Labels: perf:startup, version:6.15.0

#498 Don't overwrite existing sidekiq trace info.
  lib/new_relic/agent/instrumentation/sidekiq.rb
Labels: feedback

#537 update the test helper to avoid building error attributes once frozen.
  test/agent_helper.rb
Labels: version:6.15.0

#534 Update CI to run on ruby 3.0.0
  .github/workflows/ci.yml
  lib/new_relic/agent/vm/mri_vm.rb
  test/multiverse/lib/multiverse/envfile.rb
  test/multiverse/lib/multiverse/suite.rb
  test/multiverse/suites/agent_only/Envfile
  test/multiverse/suites/capistrano/Envfile
  test/multiverse/suites/capistrano2/Envfile
  test/multiverse/suites/curb/Envfile
  test/multiverse/suites/deferred_instrumentation/Envfile
  test/multiverse/suites/delayed_job/Envfile
  test/multiverse/suites/excon/Envfile
  test/multiverse/suites/high_security/Envfile
  test/multiverse/suites/httpclient/Envfile
  test/multiverse/suites/httprb/Envfile
  test/multiverse/suites/json/Envfile
  test/multiverse/suites/marshalling/Envfile
  test/multiverse/suites/net_http/Envfile
  test/multiverse/suites/net_http_prepend/Envfile
  test/multiverse/suites/rabbitmq/Envfile
  test/multiverse/suites/rack/Envfile
  test/multiverse/suites/rails/Envfile
  test/multiverse/suites/rails/parameter_capture_test.rb
  test/multiverse/suites/rails/view_instrumentation_test.rb
  test/multiverse/suites/rails_prepend/Envfile
  test/multiverse/suites/rake/Envfile
  test/multiverse/suites/redis/Envfile
  test/multiverse/suites/resque/Envfile
  test/multiverse/suites/sidekiq/Envfile
  test/multiverse/suites/sinatra/Envfile
  test/multiverse/suites/typhoeus/Envfile
Labels: version:6.15.0

#540 Update version and changelog for 6.15.0
  CHANGELOG.md
  lib/new_relic/version.rb
Labels: version:6.15.0
