Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-05, with the labels that each got.

#664 Change HTML links to Markdown links.
  lib/new_relic/agent/configuration/default_source.rb
Labels: version:7.1.0

#676 Remove httprb 5.0.0 from test suite
  test/multiverse/suites/httprb/Envfile
Labels: version:7.1.0

#672 Bugfix: ensure FORK_PER_JOB Resque option is correctly supported in agent
  CHANGELOG.md
  lib/new_relic/agent/agent.rb
  lib/new_relic/agent/instrumentation/resque.rb
  lib/new_relic/agent/instrumentation/resque/helper.rb
  lib/new_relic/agent/instrumentation/resque/instrumentation.rb
Labels: bug

#669 #401
  test/multiverse/suites/yajl/Envfile
Labels: community

#666 Updated Contributing Guide
  CONTRIBUTING.md
Labels: community, feedback
