Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-06, with the labels that each got.

#698 Updates resque prepend conflict check
  lib/new_relic/agent/instrumentation/resque.rb
Labels: version:upcoming

#694 Fix Rack instrumentation for "kwarg middlewares" in Ruby 3.0
  lib/new_relic/agent/instrumentation/rack/chain.rb
  lib/new_relic/agent/instrumentation/rack/prepend.rb
  test/multiverse/suites/rack/example_app.rb
  test/multiverse/suites/rack/rack_auto_instrumentation_test.rb
Labels: community

#702 Kh.fix hash thread conflict
  lib/new_relic/agent/connect/request_builder.rb
Labels: version:7.2.0

#704 Implement Expected/Ignored errors
  lib/new_relic/agent.rb
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/configuration/manager.rb
  lib/new_relic/agent/error_collector.rb
  lib/new_relic/agent/error_filter.rb
  lib/new_relic/noticed_error.rb
  test/multiverse/suites/rails/error_tracing_test.rb
  test/new_relic/agent/error_collector_test.rb
  test/new_relic/agent/error_filter_test.rb
Labels: perf:multiple-per-transaction, version:7.2.0

#708 Ensure blank SSC settings don't overwrite local expected errors
  lib/new_relic/agent/error_collector.rb
  lib/new_relic/agent/error_filter.rb
  test/multiverse/suites/sinatra/sinatra_error_tracing_test.rb
  test/new_relic/agent/error_collector_test.rb
  test/new_relic/agent/error_filter_test.rb
  test/new_relic/multiverse_helpers.rb
Labels: perf:multiple-per-transaction, version:7.2.0
