Repository newrelic/newrelic-ruby-agent, pull requests merged in 2021-04, with the labels that each got.

#629 Bugfix for Infinite Tracing not sending data
  infinite_tracing/CHANGELOG.md
  infinite_tracing/lib/infinite_tracing/client.rb
  infinite_tracing/lib/infinite_tracing/connection.rb
Labels: version:7.0.0

#605 Deprecate legacy excon instrumentation
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/excon.rb
Labels: perf:startup, version:7.0.0

#611 Implement prepend instrumentation for Rake
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/rake.rb
  lib/new_relic/agent/instrumentation/rake/chain.rb
  lib/new_relic/agent/instrumentation/rake/instrumentation.rb
  lib/new_relic/agent/instrumentation/rake/prepend.rb
  test/multiverse/suites/rake/Envfile
  test/multiverse/suites/rake/config/newrelic.yml
  test/multiverse/suites/rake/multitask_test.rb
  test/multiverse/suites/rake/rake_test.rb
  test/multiverse/suites/rake/unsupported_rake_test.rb
  test/new_relic/fake_server.rb
  test/new_relic/multiverse_helpers.rb
Labels: version:7.0.0

#603 Implement prepend instrumentation for Delayed Job
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/delayed_job/chain.rb
  lib/new_relic/agent/instrumentation/delayed_job/instrumentation.rb
  lib/new_relic/agent/instrumentation/delayed_job/prepend.rb
  lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb
  test/multiverse/suites/delayed_job/Envfile
  test/multiverse/suites/delayed_job/config/newrelic.yml
Labels: version:7.0.0

#575 Skip constructing Time for transactions
  lib/new_relic/agent/sql_sampler.rb
  test/new_relic/agent/pipe_channel_manager_test.rb
  test/new_relic/agent/sql_sampler_test.rb
  test/new_relic/agent/transaction_sampler_test.rb
Labels: community, version:7.0.0

#639 Deprecate old gems redux
  test/multiverse/suites/activemerchant/Envfile
  test/multiverse/suites/capistrano/Envfile
  test/multiverse/suites/delayed_job/Envfile
  test/multiverse/suites/excon/Envfile
  test/multiverse/suites/grape/Envfile
  test/multiverse/suites/httprb/Envfile
  test/multiverse/suites/json/Envfile
  test/multiverse/suites/memcached/Envfile
  test/multiverse/suites/padrino/Envfile
  test/multiverse/suites/rabbitmq/Envfile
  test/multiverse/suites/rails/Envfile
  test/multiverse/suites/redis/Envfile
  test/multiverse/suites/resque/Envfile
  test/multiverse/suites/sequel/Envfile
  test/multiverse/suites/sidekiq/Envfile
  test/multiverse/suites/sinatra/Envfile
  test/multiverse/suites/typhoeus/Envfile
Labels: version:7.0.0

#564 Hotfix/nil middleware browser monitoring
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/sinatra.rb
  lib/new_relic/control/frameworks/rails.rb
  lib/new_relic/control/instance_methods.rb
Labels: bug, version:7.0.0

#599 Implement prepend instrumentation for Bunny
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/bunny.rb
  lib/new_relic/agent/instrumentation/bunny/chain.rb
  lib/new_relic/agent/instrumentation/bunny/instrumentation.rb
  lib/new_relic/agent/instrumentation/bunny/prepend.rb
  test/multiverse/suites/rabbitmq/Envfile
  test/multiverse/suites/rabbitmq/config/newrelic.yml
Labels: version:7.0.0

#574 Support current Rails edge
  lib/new_relic/agent/configuration/default_source.rb
Labels: community

#636 prepend implemented for memcache
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/memcache.rb
  lib/new_relic/agent/instrumentation/memcache/chain.rb
  lib/new_relic/agent/instrumentation/memcache/dalli.rb
  lib/new_relic/agent/instrumentation/memcache/helper.rb
  lib/new_relic/agent/instrumentation/memcache/instrumentation.rb
  lib/new_relic/agent/instrumentation/memcache/prepend.rb
  lib/new_relic/dependency_detection.rb
  test/multiverse/suites/memcache/Envfile
  test/multiverse/suites/memcache/config/newrelic.yml
  test/multiverse/suites/memcache/dalli_test.rb
  test/multiverse/suites/memcache/memcache_client_test.rb
  test/multiverse/suites/memcache/memcache_test_cases.rb
  test/multiverse/suites/memcache/memcached_test.rb
Labels: version:7.0.0

#626 Implement prepend instrumentation for Sinatra
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/instrumentation/padrino.rb
  lib/new_relic/agent/instrumentation/padrino/chain.rb
  lib/new_relic/agent/instrumentation/padrino/instrumentation.rb
  lib/new_relic/agent/instrumentation/padrino/prepend.rb
  lib/new_relic/agent/instrumentation/sinatra.rb
  lib/new_relic/agent/instrumentation/sinatra/chain.rb
  lib/new_relic/agent/instrumentation/sinatra/ignorer.rb
  lib/new_relic/agent/instrumentation/sinatra/instrumentation.rb
  lib/new_relic/agent/instrumentation/sinatra/prepend.rb
  test/multiverse/suites/deferred_instrumentation/Envfile
  test/multiverse/suites/deferred_instrumentation/config/newrelic.yml
  test/multiverse/suites/padrino/Envfile
  test/multiverse/suites/padrino/config/newrelic.yml
  test/multiverse/suites/padrino/padrino_test.rb
  test/multiverse/suites/sinatra/Envfile
  test/multiverse/suites/sinatra/config/newrelic.yml
  test/multiverse/suites/sinatra/sinatra_test_cases.rb
  test/new_relic/agent/instrumentation/sinatra_test.rb
Labels: version:7.0.0

#640 Bump to 7.0.0
  CHANGELOG.md
  lib/new_relic/version.rb
Labels: version:7.0.0

#645 Fix passing keyword arguments in ruby 3.0
  lib/new_relic/agent/instrumentation/middleware_proxy.rb
  test/new_relic/agent/instrumentation/middleware_proxy_test.rb
Labels: community

#641 Decrease number of concurrent CI jobs
  .github/workflows/ci.yml
  test/multiverse/lib/multiverse/runner.rb
Labels: version:7.0.0

#660 Add recently reported prepend conflicts
  CHANGELOG.md
  lib/new_relic/agent/instrumentation/net_http.rb
  lib/new_relic/agent/instrumentation/redis.rb
  lib/new_relic/agent/instrumentation/resque.rb
Labels: version:7.1.0
