Repository newrelic/newrelic-ruby-agent, pull requests merged in 2022-01, with the labels that each got.

#882 Make generate_guid faster
  lib/new_relic/agent/guid_generator.rb
Labels: perf:multiple-per-transaction, community, pending-merge, version: 8.4.0

#894 Update setup-ruby version on actions
  .github/workflows/release.yml
  .github/workflows/snyk.yml
Labels: pending-merge, version: 8.4.0

#895 Update Sidekiq, Puma versions in multiverse
  test/multiverse/suites/rack/Envfile
  test/multiverse/suites/sidekiq/Envfile
Labels: pending-merge

#896 document software needed for multiverse testing
  .gitignore
  Brewfile
  CONTRIBUTING.md
  infinite_tracing/newrelic-infinite_tracing.gemspec
  newrelic_rpm.gemspec
  test/multiverse/README.md
  test/multiverse/suites/mongo/helpers/mongo_server.rb
  test/new_relic/license_test.rb
Labels: pending-merge, version: 8.4.0
