Repository newrelic/newrelic-ruby-agent, pull requests merged in 2023-10, with the labels that each got.

#2246 Skip Active Support Logger instrumentation for Rails 7.1
  lib/new_relic/agent/instrumentation/active_support_logger.rb
  test/multiverse/suites/rails/active_support_logger_test.rb
Labels: core technology, rails

#2250 #2247, removes unused variable warnings in tests suite
  test/new_relic/agent/configuration/manager_test.rb
  test/new_relic/agent/monitors/synthetics_monitor_test.rb
  test/new_relic/agent/tracer_test.rb
  test/new_relic/dependency_detection_test.rb
Labels: community, hacktoberfest-accepted

#2256 Add and Replace SLASH and ROOT constants
  lib/new_relic/agent/instrumentation/active_record_helper.rb
  lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb
  lib/new_relic/agent/instrumentation/roda/roda_transaction_namer.rb
  lib/new_relic/agent/instrumentation/sinatra/transaction_namer.rb
  lib/new_relic/agent/messaging.rb
  lib/new_relic/agent/rules_engine.rb
  lib/new_relic/agent/transaction/message_broker_segment.rb
  lib/new_relic/agent/transaction/request_attributes.rb
  lib/new_relic/agent/utilization/gcp.rb
  lib/new_relic/constants.rb
Labels: community, hacktoberfest-accepted

#2261 Fix deprecation warning from sidekiq error handler
  lib/new_relic/agent/instrumentation/sidekiq.rb
Labels: community

#2278 add instrumentation for HTTPX
  CHANGELOG.md
  lib/new_relic/agent/configuration/default_source.rb
  lib/new_relic/agent/http_clients/httpx_wrappers.rb
  lib/new_relic/agent/instrumentation/httpx.rb
  lib/new_relic/agent/instrumentation/httpx/chain.rb
  lib/new_relic/agent/instrumentation/httpx/instrumentation.rb
  lib/new_relic/agent/instrumentation/httpx/prepend.rb
  test/multiverse/lib/multiverse/runner.rb
  test/multiverse/suites/httpx/Envfile
  test/multiverse/suites/httpx/config/newrelic.yml
  test/multiverse/suites/httpx/httpx_instrumentation_test.rb
Labels: hacktoberfest-accepted

#2292 Updated documentation for NewRelic::Agent#add_custom_log_attributes method to be more clear
  lib/new_relic/agent.rb
Labels: community, hacktoberfest-accepted

#2294 Cleanup of duplicated constants from individual HTTP wrapper classes to abstract class
  lib/new_relic/agent/http_clients/abstract.rb
  lib/new_relic/agent/http_clients/async_http_wrappers.rb
  lib/new_relic/agent/http_clients/curb_wrappers.rb
  lib/new_relic/agent/http_clients/ethon_wrappers.rb
  lib/new_relic/agent/http_clients/excon_wrappers.rb
  lib/new_relic/agent/http_clients/http_rb_wrappers.rb
  lib/new_relic/agent/http_clients/httpclient_wrappers.rb
  lib/new_relic/agent/http_clients/httpx_wrappers.rb
  lib/new_relic/agent/http_clients/net_http_wrappers.rb
  lib/new_relic/agent/http_clients/typhoeus_wrappers.rb
Labels: community, hacktoberfest-accepted
